project_name: Terms And Conditions Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Terms And Conditions Inbound
    source: GITHUB
    repo: vcep-int-terms-and-conditions-inbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-terms-and-conditions-inbound logic-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-terms-and-conditions-inbound logic-CI
        job: Job
        project: RCXP
