project_name: Ccs Inbound Orders
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Ccs Inbound Orders
    source: GITHUB
    repo: vcep-int-ccs-inbound-orders
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: vcep-int-ccs-inbound-orders-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: vcep-int-ccs-inbound-orders-CI
        job: Job
        project: RCXP
