project_name: Consumer Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  -
    name: Consumer Inbound
    source: GITHUB
    repo: vcep-int-consumer-inbound
    project: RCXP
    environments:  
      -
        name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-consumer-inbound-logic CI
        job: Job
      -
        name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-consumer-inbound-logic CI
        job: Job
