project_name: Documentapi Client Lib
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Documentapi Client Lib
    source: GITHUB
    repo: vcep-int-documentApi-client-lib
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-documentApi-client-lib-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-documentApi-client-lib-CI
        job: Job
        project: RCXP
