project_name: Social Leads Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Social Leads Inbound
    source: GITHUB
    repo: vcep-int-social-leads-inbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-social-leads-logic CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-social-leads-logic CI
        job: Job
        project: RCXP
