project_name: Consumer Outbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Consumer Outbound
    source: GITHUB
    repo: vcep-int-consumer-outbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-consumer-outbound-logic CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-consumer-outbound-logic CI
        job: Job
        project: RCXP
