project_name: Payment Order Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Payment Order Inbound
    source: GITHUB
    repo: vcep-int-payment-order-inbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-payment-order-inbound-function-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-payment-order-inbound-function-CI
        job: Job
        project: RCXP
