project_name: Fras Inbound Account
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  -
    name: Fras Inbound Account
    source: GITHUB
    repo: vcep-int-fras-inbound-account
    project: RCXP
    environments:  
      -
        name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: vcep-int-fras-inbound-account-CI
        job: Job
      -
        name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: vcep-int-fras-inbound-account-CI
        job: Job
