project_name: Salesdata V2 Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Salesdata V2 Inbound
    source: GITHUB
    repo: vcep-int-salesdata-v2-inbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-sales-data-v2-logic-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-sales-data-v2-logic-CI
        job: Job
        project: RCXP
