project_name: Fleet Customer Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  -
    name: Fleet Customer Inbound
    source: GITHUB
    repo: vcep-int-fleet-customer-inbound
    project: RCXP
    environments:  
      -
        name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-fleet-customer-logic CI
        job: Job
      -
        name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-fleet-customer-logic CI
        job: Job
