project_name: Api Lib
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Api Lib
    source: GITHUB
    repo: vcep-int-api-lib
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-api-nuget CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-api-nuget CI
        job: Job
        project: RCXP
