project_name: Ssa Outbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  -
    name: Ssa Outbound
    source: GITHUB
    repo: vcep-int-ssa-outbound
    project: RCXP
    environments:  
      -
        name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-ssa-outbound-logic-CI
        job: Job
      -
        name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-ssa-outbound-logic-CI
        job: Job
