project_name: Log Request Util
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Log Request Util
    source: GITHUB
    repo: vcep-int-log-request-util
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-log-request-logic-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-log-request-logic-CI
        job: Job
        project: RCXP
