project_name: Spin Api
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Spin Api
    source: GITHUB
    repo: vcep-int-spin-api
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-spin-api-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-spin-api-CI
        job: Job
        project: RCXP
