project_name: Azure Function Lib
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Azure Function Lib
    source: GITHUB
    repo: vcep-int-azure-function-lib
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-azure-function-nuget CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-azure-function-nuget CI
        job: Job
        project: RCXP
