project_name: Spin Inbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Spin Inbound
    source: GITHUB
    repo: vcep-int-spin-inbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-spin-inbound-logic GITHUB
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-spin-inbound-logic GITHUB
        job: Job
        project: RCXP
