project_name: Salesforce Events Outbound
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  - name: Salesforce Events Outbound
    source: GITHUB
    repo: vcep-int-salesforce-events-outbound
    environments:  
      - name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-salesforce-httpevents-logic-CI
        job: Job
        project: RCXP
      - name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-salesforce-httpevents-logic-CI
        job: Job
        project: RCXP
