project_name: Customer Order Inboud
cluster: Customer Care
team: Vcep Integration Team
tags: [Integration Platform, VCEP]
services:
  -
    name: Customer Order Inboud
    source: GITHUB
    repo: vcep-int-customer-order-inboud
    project: RCXP
    environments:  
      -
        name: uat
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-customer-order-logic CI
        job: Job
      -
        name: prod-emea
        branch: master
        pipeline: AZURE_PIPELINES
        workflow: int-customer-order-logic CI
        job: Job
